# Synthetic / AI-generated image detector (B-Free, CVPR 2025) for passport images.
#
# Model: DINOv2 (w/ registers) ViT backbone, trained via a "bias-free" paradigm —
# fake images generated as self-conditioned Stable Diffusion reconstructions of real
# ones, so the model learns actual generation artifacts rather than spurious dataset
# biases. Source: https://github.com/grip-unina/B-Free (same research group as TruFor)
#
# This stage answers "was this image (or document region) generated by an AI model
# from scratch" — a gap neither TruFor (local-tampering forensics) nor an MRZ check
# (content/checksum validation) covers. It does NOT detect local splicing/editing of
# an otherwise-real photo; that's TruFor's job.
#
# Runs in a separate 'bfree' Conda env (torch 2.0.1/timm>=1.0.12), incompatible with
# the 'trufor' env's older pinned stack. Called as a subprocess from the pipeline
# orchestrator.
#
# All processing is local. No network calls are made from this script.

import os
import sys
import json
import argparse

import torch
from PIL import Image
from torchvision.transforms import Compose

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'code'))

from utils.normalization import get_list_norm
from networks import get_network, load_weights

import yaml

DEFAULT_MODEL_NAME = 'BFREE_dino2reg4'


def parse_args():
    parser = argparse.ArgumentParser(
        description='Run B-Free (CVPR 2025) synthetic/AI-generated image detector on '
                     'a single image. Complementary to TruFor, not a replacement.')
    parser.add_argument('--image', required=True, help='path to input image')
    parser.add_argument('--output', required=True, help='output directory')
    parser.add_argument('-g', '--gpu', type=int, default=0, help='GPU index, -1 for CPU')
    parser.add_argument('--model', type=str, default=DEFAULT_MODEL_NAME)
    parser.add_argument('--weights_dir', type=str,
                         default=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'weights'))
    return parser.parse_args()


def get_config(model_name, weights_dir):
    config_path = os.path.join(weights_dir, model_name, 'config.yaml')
    if not os.path.isfile(config_path):
        raise FileNotFoundError(
            f'Config not found at "{config_path}". Download weights from '
            f'https://www.grip.unina.it/download/prog/B-Free/weights/BFREE_dino2reg4.zip '
            f'and unzip into "weights/".')
    with open(config_path) as fid:
        data = yaml.load(fid, Loader=yaml.FullLoader)
    model_path = os.path.join(weights_dir, model_name, data['weights_file'])
    return model_path, data['arch'], data['norm_type']


def load_model(model_name, weights_dir, device):
    model_path, arch, norm_type = get_config(model_name, weights_dir)
    model = load_weights(get_network(arch), model_path)
    model = model.to(device).eval()
    transform = Compose(get_list_norm(norm_type))
    return model, transform


def run_inference(model, transform, image_path, device):
    image = transform(Image.open(image_path).convert('RGB'))
    image = image.unsqueeze(0)

    with torch.no_grad():
        out_tens = model(image.to(device)).cpu().numpy()

        if out_tens.shape[1] == 1:
            logit = out_tens[:, 0]
        elif out_tens.shape[1] == 2:
            logit = out_tens[:, 1] - out_tens[:, 0]
        else:
            raise ValueError(f'Unexpected output shape: {out_tens.shape}')

    logit = float(logit.item())
    synthetic_prob = float(torch.sigmoid(torch.tensor(logit)).item())
    return logit, synthetic_prob


def risk_label(score):
    if score is None:
        return 'unavailable'
    if score < 0.33:
        return 'low'
    if score < 0.66:
        return 'medium'
    return 'high'


def save_outputs(out_dir, basename, logit, synthetic_prob, model_name):
    os.makedirs(out_dir, exist_ok=True)

    result = {
        'model': f'B-Free ({model_name}, CVPR 2025, DINOv2-based)',
        'result_type': 'synthetic / AI-generated image risk',
        'disclaimer': (
            'B-Free detects whether an image was generated by an AI model (e.g. '
            'Stable Diffusion), trained via a bias-free self-conditioned paradigm to '
            'reduce spurious dataset shortcuts. It does NOT detect local splicing or '
            'editing of an otherwise-real photo (that is TruFor\'s job) and is not a '
            'passport-authentication system. Negative logits indicate real, positive '
            'logits indicate AI-generated, per the model\'s own training convention.'
        ),
        'raw_logit': logit,
        'synthetic_probability': synthetic_prob,
        'risk_label': risk_label(synthetic_prob),
    }
    with open(os.path.join(out_dir, f'{basename}_bfree_result.json'), 'w') as f:
        json.dump(result, f, indent=2)

    return result


def main():
    args = parse_args()
    device = f'cuda:{args.gpu}' if args.gpu >= 0 and torch.cuda.is_available() else 'cpu'
    if args.gpu >= 0 and not torch.cuda.is_available():
        print('Warning: CUDA not available, falling back to CPU.')

    model, transform = load_model(args.model, args.weights_dir, device)
    logit, synthetic_prob = run_inference(model, transform, args.image, device)

    basename = os.path.splitext(os.path.basename(args.image))[0]
    result = save_outputs(args.output, basename, logit, synthetic_prob, args.model)

    print(f'logit score: {logit:.3f}')
    print(json.dumps(result, indent=2))
    print(f'=> outputs saved to {os.path.abspath(args.output)}')


if __name__ == '__main__':
    main()
